"""Update tables

Revision ID: 0f089be026ba
Revises: 9a6f3862ab70
Create Date: 2026-02-13 17:17:03.890953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f089be026ba'
down_revision: Union[str, None] = '9a6f3862ab70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Wallet_operation_type', table_name='Wallet')
    op.drop_column('Wallet', 'operation_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Wallet', sa.Column('operation_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_Wallet_operation_type', 'Wallet', ['operation_type'], unique=False)
    # ### end Alembic commands ###
